export const standardEmojis = [
	{ emoji: '😀', character: '😀' },
	{ emoji: '😁', character: '😁' },
	{ emoji: '😂', character: '😂' },
	{ emoji: '🤣', character: '🤣' },
	{ emoji: '😊', character: '😊' },
	{ emoji: '😍', character: '😍' },
	{ emoji: '🤔', character: '🤔' },
	{ emoji: '👍', character: '👍' },
	{ emoji: '🙏', character: '🙏' },
	{ emoji: '✨', character: '✨' },
	{ emoji: '🔥', character: '🔥' },
	{ emoji: '🍀', character: '🍀' },
	{ emoji: '🍕', character: '🍕' },
	{ emoji: '☕', character: '☕' },
	{ emoji: '🏃', character: '🏃' },
	{ emoji: '📎', character: '📎' },
	{ emoji: '💡', character: '💡' },
	{ emoji: '🛠️', character: '🛠️' }
];
